spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iris_license
    username: postgres
    password: dipak
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: ESMSHikariCP

  security:
    user:
      name: admin
      password: velox@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
