spring:
  datasource:
    url: jdbc:sqlite:./data/license.db
    driver-class-name: org.sqlite.JDBC
  security:
    user:
      name: admin
      password: velox@123

  jpa:
    database-platform: com.velox.license.irislicenseserver.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082


